version: '3.1'

networks:
  ridwands-network:
volumes:
  ridwands_volume_mongodb:
 
services:
  db:
    image: mongo:latest
    networks:
      - ridwands-network
    environment:
    - "TZ=Asia/Jakarta" # offset = -05:00 / DST -04:00
    ports:
      - 27017:27017
    volumes:
      - ridwands_volume_mongodb
